#version 120

varying vec3 f_texCoord;
uniform samplerCube cubemap;

// DOCUMENTACION SOBRE LA IMPLEMENTACION OPCIONAL
// LAS INFORMACIÓN PARA PODER REALIZAR ESTA SECCIÓN DEL OBJETIVO OPCIONAL SE OBTUVO A TRAVES DE EL DOCUMENTO FACILITADO EN EGELA EN EL QUE SE DESCRIBE LA PRACTICA.
// ADEMAS, SE REALIZÓ UNA BREVE TUTORÍA PARA PODER ACLARAR DUDAS MUY PUNTUALES QUE AUNQUE NO TENIAN UNA GRAN REPERCUSIÓN A LA HORA DE SACAR ESTE SHADER FUERON 
// DE GRAN AYUDA PARA ENTENDER LO QUE SE REALIZABA A TRAVES DEL CODIGO.


// To sample a texel from a cubemap, use "textureCube" function:
//
// vec4 textureCube(samplerCube sampler, vec3 coord);

void main() {
	vec4 texel = textureCube(cubemap, f_texCoord);
	gl_FragColor = texel;
	
}
